### ISSUE TITLE
Discussion: 開発の進め方について

### ISSUE THREAD

**Issue by kazuhe** [kazuhe/nome#1]
## 🎉 Goal

開発の進め方について議論し、大まかな開発フローが決まればこのissueをもとに`CONTRIBUTING.md`を作成する。

## 📝 Detail

基本はissueで「追加したい機能の宣言」や「相談・議論」を行いながら開発を進めていければと思います。
あと、projectを作ってるのでこちらでタスク管理的なのやりたい。
https://github.com/kazuhe/nome/projects/1

例: 新しい機能を追加したい場合

1. 対応範囲などを明確にしてissueを作成
2. 調整が必要であれば調整し問題なければ開発を進める
3. 実装が完了したらPRを作成
4. 自分以外のメンバがレビュー
5. 問題なければマージ
6. issueをclose

https://github.com/kazuhe/nome/tree/main/.github/ISSUE_TEMPLATE
issueテンプレートを作成してます。変更や追加等あれば現時点では自由にしてもらって大丈夫です！

その他決めておくべき事ありますかね🤔

- ブランチルール
- コミットメッセージのルール

とかかな。

**Comment by ytk6565** [comment]
@kazuhe 
> ブランチルール

会社の運用ルールに従うなら作業ブランチは `feature/issue-XXXX` の形式で Issue 番号でブランチを切って、リリースブランチは `release/XXXX` ですかね。
リリースブランチは Backlog の課題の番号から作成しているので、何かしら工夫が必要かもしれないですね。

> コミットメッセージのルール

しっかりコミットメッセージにルールを取り入れた経験ないです。
commitlint 導入して都度カスタマイズしていけたらと思いました。

https://github.com/conventional-changelog/commitlint

**Comment by kazuhe** [comment]
@ytk6565 

コメントありがとうございます！なるほど。

> 作業ブランチは feature/issue-XXXX の形式で Issue 番号でブランチを切って

これはそのまま採用しましょう！
なるべく同じ運用に沿いたいですがリリースブランチは必要ないかもって思ってきました...

一旦、作業ブランチからmainにそのままマージする方向でいきますか？
ブランチルールに関してはその方がシンプルで良い気がしました。

> commitlint 導入して都度カスタマイズしていけたらと思いました。

おぉ！いいですね！これは開発環境を準備する段階で試してみます！

**Comment by ytk6565** [comment]
@kazuhe 
> なるべく同じ運用に沿いたいですがリリースブランチは必要ないかもって思ってきました...
> 
> 一旦、作業ブランチからmainにそのままマージする方向でいきますか？
> ブランチルールに関してはその方がシンプルで良い気がしました。

そうですね。シンプルに作業ブランチのみで良いと思います！

**Comment by kazuhe** [comment]
### [WIP] 開発ルール
- 基本ルール
  - 基本的にはissueで対応範囲や実装方法を明確にした後にそれに紐づくPRを作成する
    - 議論したい内容がある場合でもissueテンプレートをもとにissueを立てる
  - 自分以外のメンバがPRのレビューを行い確認できたらマージを行う
  - 既に存在するissueをセルフアサインするか、新しくissueをたてて作業を行う
- ブランチルール
  - 作業ブランチは `feature/issue-XXXX` の形式でIssue番号でブランチを切る
- コミットルール
  - commitlintを試してみる

**Comment by kazuhe** [comment]
https://github.com/kazuhe/nome/pull/25
