### ISSUE TITLE
Feature: 開発環境の改善

### ISSUE THREAD

**Issue by kazuhe** [kazuhe/nome#4]
## 🎉 Goal

開発環境の改善の為に必要なライブラリのinstallと設定を行う。
なお、パッケージ共通で扱えるライブラリ（TypeScript等）は親のpackage.jsonで`install`する。

## 📷 Image

なし

## 📖 Reference (optional)

- https://github.com/kazuhe/nome/pull/3

## 📎 Tasks (optional)

- [x] #7
- [x] #18
- [x] #6
- [x] #8
- [x] #12
- [x] #13
- [x] #15

**Comment by ytk6565** [comment]
@kazuhe 
社内と同じように各タスクの右側に自分の名前入れるような形で担当する形とかで良いですかね？
他に良いやり方などあれば教えていただきたいです！

**Comment by kazuhe** [comment]
![スクリーンショット 2021-07-14 22 31 22](https://user-images.githubusercontent.com/57878514/125630641-97acf7b1-ef42-40a2-814d-7384d6f20a08.png)

ちょっと面倒かもですが↑の様にタスクにhoverすると「Open convert to issue」と表示されてissue分割できるっぽいので、自分がやりたいタスクはissueたててセルフアサインして実装する感じでいきます？

> 社内と同じように各タスクの右側に自分の名前入れるような形

これだと変更しても気づきにくい気がするので！

**Comment by ytk6565** [comment]
> ちょっと面倒かもですが↑の様にタスクにhoverすると「Open convert to issue」と表示されてissue分割できるっぽいので、自分がやりたいタスクはissueたててセルフアサインして実装する感じでいきます？

これでいきましょう！ありがとうございます！

**Comment by ytk6565** [comment]
> mainブランチにマージすると本番公開

クライアントとサーバーどちらも Heroku にアップロードする想定ですか？
Heroku をあまり利用した経験がなく把握できておらず申し訳ないです。

**Comment by ytk6565** [comment]
アップロードの方法に関して承知致しました！

> このタスクは僕の方で対応します！🐢
（できるかは分からないw）

何かできることあれば言ってください！
